apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: prueba
spec:
  selector:
    app: demo
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP
