---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes2025
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/JulianOsorioCastro/Kubernetes2025.git
