apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes2025
  namespace: flux-system
spec:
  interval: 1m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes2025
  targetNamespace: prueba-integracion
  timeout: 2m
