apiVersion: v1
kind: Namespace
metadata:
  name: prueba-integracion
  labels:
    entorno: prueba
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-prueba
  namespace: prueba-integracion
  labels:
    app: demo
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
