apiVersion: v1
kind: Pod
metadata:
  name: pod-prueba-1
  labels:
    app: prueba
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-prueba-2
  labels:
    app: prueba
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
