apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: prueba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: nginx:1.25
        ports:
        - containerPort: 80
